apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-auto-collections
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin-auto-collections
  template:
    metadata:
      labels:
        app: jellyfin-auto-collections
    spec:
      containers:
        - name: jellyfin-auto-collections
          image: artifactory.local.hejsan.xyz/docker/ghomashudson/jellyfin-auto-collections:latest@sha256:b0c31c02312d8389ef04da86b8007a1362e93118e20a1aa72bc2d8ae560ce5ce
          #command: ["/bin/sh", "-c", "sleep infinity"]
          #args: ["-c", "exec /bin/sh"]
          envFrom:
            - secretRef:
                name: jellyfin-auto-collections-secret
          volumeMounts:
            - name: config-yaml
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: config-yaml
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.1"
      volumes:
        - name: config-yaml
          configMap:
            name: jellyfin-auto-collections-config
