apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - namespace.yaml
  - kube-prometheus-stack
  - gotify
  - alertmanager-gotify-bridge
  - alerts

commonLabels:
  app.kubernetes.io/part-of: monitoring