apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: artifactory.local.hejsan.xyz/docker/linuxserver/sonarr:4.0.16
          ports:
            - containerPort: 8989
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: sonarr-config-pvc
              mountPath: /config
            - name: shared-storage
              mountPath: /mnt/storage
          resources:
            limits:
              memory: 1000Mi
              cpu: "1"
            requests:
              memory: 250Mi
              cpu: "0.1"
      volumes:
        - name: sonarr-config-pvc
          persistentVolumeClaim:
            claimName: sonarr-config-pvc-sonarr-0
        - name: shared-storage
          persistentVolumeClaim:
            claimName: media-shared-nfs-pvc
