apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: artifactory.local.hejsan.xyz/docker/linuxserver/prowlarr:2.3.1-nightly@sha256:9f2088ecece03ceb0005d2346347e74b3adb493f164deb333b7cf4f8dd41d2ae
          ports:
            - containerPort: 9696
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: prowlarr-config-pvc
              mountPath: /config
            - name: shared-storage
              mountPath: /mnt/storage
          resources:
            limits:
              memory: 400Mi
              cpu: "1"
            requests:
              memory: 200Mi
              cpu: "0.2"
      volumes:
        - name: prowlarr-config-pvc
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc-prowlarr-0
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-nfs-pvc
