apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: artifactory.local.hejsan.xyz/docker/linuxserver/prowlarr:2.3.2-nightly@sha256:92fb2bde29cc733ac462df01c1bf78f296a677e4d24a3c6742d58b7cc276ffc1
          ports:
            - containerPort: 9696
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: prowlarr-config-pvc
              mountPath: /config
            - name: shared-storage
              mountPath: /mnt/storage
          resources:
            limits:
              memory: 400Mi
              cpu: "1"
            requests:
              memory: 200Mi
              cpu: "0.2"
      volumes:
        - name: prowlarr-config-pvc
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc-prowlarr-0
        - name: shared-storage
          persistentVolumeClaim:
            claimName: media-shared-nfs-pvc
