apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - github-runner.yaml

labels:
  - includeSelectors: true
    pairs:
      app: app

replacements:
  - source:
      kind: Deployment
      fieldPath: metadata.name
    targets:
      - select:
          kind: Service
        fieldPaths:
          - metadata.name
          - spec.selector.app
      - select:
          kind: IngressRoute
        fieldPaths:
          - metadata.name
          - spec.routes.[kind=Rule].services.0.name
      - select:
          kind: HelmRelease
        fieldPaths:
          - spec.values.runnerScaleSetName
