apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netbootxyz

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - persistence.yaml
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app: netbootxyz
