---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz
spec:
  type: LoadBalancer
  loadBalancerIP: ${NETBOOT_IP}
  selector:
    app: netbootxyz
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: tftp
      port: 69
      targetPort: 69
      protocol: UDP
    - name: assets
      port: 80
      targetPort: 80
      protocol: TCP
