apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: artifactory.local.hejsan.xyz/docker/linuxserver/radarr:6.1.0-nightly@sha256:08344e0e278e2b05a54b257927a5cf1407786a54a3a12ebdadbf25e9fe6809cb
          ports:
            - containerPort: 7878
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: radarr-config-pvc
              mountPath: /config
            - name: shared-storage
              mountPath: /mnt/storage
          resources:
            limits:
              memory: 900Mi
              cpu: "1"
            requests:
              memory: 500Mi
              cpu: "0.5"
      volumes:
        - name: radarr-config-pvc
          persistentVolumeClaim:
            claimName: radarr-config-pvc-radarr-0
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-nfs-pvc
