apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: artifactory.local.hejsan.xyz/docker/linuxserver/radarr:6.1.1-nightly@sha256:9b9f5165298f11f6e1273939b96f6c3eedd0aea8a57fc76e2aa46f6729402cb9
          ports:
            - containerPort: 7878
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: radarr-config-pvc
              mountPath: /config
            - name: shared-storage
              mountPath: /mnt/storage
          resources:
            limits:
              memory: 900Mi
              cpu: "1"
            requests:
              memory: 500Mi
              cpu: "0.5"
      volumes:
        - name: radarr-config-pvc
          persistentVolumeClaim:
            claimName: radarr-config-pvc-radarr-0
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-nfs-pvc
