apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: artifactory.local.hejsan.xyz/docker/linuxserver/transmission:4.0.6
          ports:
            - containerPort: 9091
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: transmission-config-pvc
              mountPath: /config
            - name: shared-storage
              mountPath: /mnt/storage
          resources:
            limits:
              memory: 400Mi
              cpu: "0.3"
            requests:
              memory: 100Mi
              cpu: "0.1"
      volumes:
        - name: transmission-config-pvc
          persistentVolumeClaim:
            claimName: transmission-config-pvc-transmission-0
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-nfs-pvc
