apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkrr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: checkrr
  template:
    metadata:
      labels:
        app: checkrr
    spec:
      initContainers:
        - name: init-checkrr-db
          image: busybox@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
          command:
            - sh
            - -c
            - |
              mkdir -p /checkrr-config/database && touch /checkrr-config/database/checkrr.db
              echo "Listing /checkrr-config:"
              ls -l /checkrr-config
              echo "Listing /checkrr-config/database:"
              ls -l /checkrr-config/database
          volumeMounts:
            - name: checkrr-config-pvc
              mountPath: /checkrr-config
        - name: init-badfiles-csv
          image: busybox@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
          command:
            - sh
            - -c
            - |
              mkdir -p /checkrr-config && touch /checkrr-config/badfiles.csv
          volumeMounts:
            - name: checkrr-config-pvc
              mountPath: /checkrr-config
      containers:
        - name: checkrr
          image: artifactory.local.hejsan.xyz/docker/aetaric/checkrr:3.6.0@sha256:b72a31fcba88ec79cc2e07b69f2343b5da3594ba611c2346402e90f2781615f3
          ports:
            - containerPort: 8585
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          livenessProbe:
            httpGet:
              path: /api/stats/current
              port: 8585
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/stats/current
              port: 8585
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          volumeMounts:
            - name: checkrr-config-volume
              mountPath: /etc/checkrr.yaml
              subPath: checkrr.yaml
            - name: shared-storage
              mountPath: /mnt/storage
            - name: checkrr-config-pvc
              mountPath: /checkrr-config/
          resources:
            limits:
              memory: 500Mi
              cpu: "1"
            requests:
              memory: 320Mi
              cpu: "0.1"
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: media-shared-nfs-pvc
        - name: checkrr-config-volume
          secret:
            secretName: checkrr-config
        - name: checkrr-config-pvc
          persistentVolumeClaim:
            claimName: checkrr-config-pvc-checkrr-0
