apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkrr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: checkrr
  template:
    metadata:
      labels:
        app: checkrr
    spec:
      initContainers:
        - name: init-checkrr-db
          image: busybox@sha256:e226d6308690dbe282443c8c7e57365c96b5228f0fe7f40731b5d84d37a06839
          command:
            - sh
            - -c
            - |
              mkdir -p /checkrr-config/database && touch /checkrr-config/database/checkrr.db
              echo "Listing /checkrr-config:"
              ls -l /checkrr-config
              echo "Listing /checkrr-config/database:"
              ls -l /checkrr-config/database
          volumeMounts:
            - name: checkrr-config-pvc
              mountPath: /checkrr-config
        - name: init-badfiles-csv
          image: busybox@sha256:e226d6308690dbe282443c8c7e57365c96b5228f0fe7f40731b5d84d37a06839
          command:
            - sh
            - -c
            - |
              mkdir -p /checkrr-config && touch /checkrr-config/badfiles.csv
          volumeMounts:
            - name: checkrr-config-pvc
              mountPath: /checkrr-config
      containers:
        - name: checkrr
          image: artifactory.local.hejsan.xyz/docker/aetaric/checkrr:3.5.4
          ports:
            - containerPort: 8585
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          livenessProbe:
            httpGet:
              path: /api/stats/current
              port: 8585
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/stats/current
              port: 8585
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          volumeMounts:
            - name: checkrr-config-volume
              mountPath: /etc/checkrr.yaml
              subPath: checkrr.yaml
            - name: shared-storage
              mountPath: /mnt/storage
            - name: checkrr-config-pvc
              mountPath: /checkrr-config/
          resources:
            limits:
              memory: 500Mi
              cpu: "1"
            requests:
              memory: 320Mi
              cpu: "0.1"
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: media-shared-nfs-pvc
        - name: checkrr-config-volume
          secret:
            secretName: checkrr-config
        - name: checkrr-config-pvc
          persistentVolumeClaim:
            claimName: checkrr-config-pvc-checkrr-0
