apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: artifactory.local.hejsan.xyz/docker/linuxserver/bazarr:1.5.4@sha256:f00df1c88545a23d3d22ca10f5ae5b7ee9359db1d28756b7f8a43cec624042fd
          ports:
            - containerPort: 6767
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: bazarr-config-pvc
              mountPath: /config
            - name: shared-storage
              mountPath: /mnt/storage
          resources:
            limits:
              memory: 500Mi
              cpu: "1"
            requests:
              memory: 320Mi
              cpu: "0.1"
      volumes:
        - name: bazarr-config-pvc
          persistentVolumeClaim:
            claimName: bazarr-config-pvc-bazarr-0
        - name: shared-storage
          persistentVolumeClaim:
            claimName: media-shared-nfs-pvc
