apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gotify
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gotify.${DOMAIN_INTERNAL}`)
      services:
        - name: gotify
          port: 8080
  tls:
    secretName: ${CERT_SECRET_INTERNAL}
