apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api
  - web
  - scraper
  - database
  - arc-runner-setup.yaml

labels:
  - includeSelectors: true
    pairs:
      app_group: new-new-boplats
