apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production infrastructure controllers overlay
# Includes ALL base controllers for full production deployment

resources:
  # ALL infrastructure controllers
  - ../../base/controllers/cert-manager/
  - ../../base/controllers/ingress-traefik/
  - ../../base/controllers/longhorn/
  - ../../base/controllers/mongodb-operator/
  - ../../base/controllers/openebs/
  - ../../base/controllers/reflector/
