---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-gotify-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-gotify-bridge
  template:
    metadata:
      labels:
        app: alertmanager-gotify-bridge
    spec:
      containers:
        - name: bridge
          image: artifactory.local.hejsan.xyz/docker/druggeri/alertmanager_gotify_bridge:2.3
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: GOTIFY_ENDPOINT
              value: "http://gotify.monitoring.svc.cluster.local:8080/message"
            - name: GOTIFY_TOKEN
              value: "A7TvHUAUjtqng3X"
            - name: DEFAULT_PRIORITY
              value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-gotify-bridge
  namespace: monitoring
spec:
  selector:
    app: alertmanager-gotify-bridge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
