---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: alertmanager-gotify-bridge
  app.kubernetes.io/part-of: monitoring
resources:
  - deployment.yaml
