apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - release.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kube-prometheus-stack
      prometheus: "true"
    includeSelectors: true
