apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: Environment overlays must provide:
# - my-join-secret.yaml (containing my-joinkey-secret with join.key)
# - my-masterkey-secret.yaml (containing my-masterkey-secret with master.key)

resources:
  - namespace.yaml
  - release.yaml
  - source.yaml
  # - persistence.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: artifactory-release-values
    namespace: artifactory
    files:
      - values.yaml=release-values.yaml