apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - namespace.yaml
  - bazarr
  # - overseerr
  - prowlarr
  - radarr
  - sonarr
  - transmission
  - jellyfin
  - cleanuperr
  - checkrr
  - reiverr
