{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.appName }}.{{ .Values.ingress.domain }}`)
      kind: Rule
      services:
        - name: {{ .Values.appName }}
          port: http
  tls:
    secretName: {{ .Values.ingress.certSecret }}
{{- end }}
