apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-app-config.yaml
  - traefik-dashboard
  - downloader
  - artifactory
  - cloudflare-ddns
  - it-tools
  - actions-runner
  - renovate-bot
  - new-new-boplats
  - monitoring
  - media
  - longhorn
  - persistence
  - smart-home
  - headscale
  - immich

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: default
    unsetOnly: true

configurations:
  - kustomizeconfig.yaml
