apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-statefulset-rules.yaml
  - grafana-rules.yaml

labels:
  - pairs:
      app.kubernetes.io/name: prometheus-rules
    includeSelectors: true
