apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: container-registry

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - middleware.yaml
  - service.yaml
  - persistence.yaml
  - secret.yaml